services:
  web:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_web_prod
    command: /start
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.prod

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_celery_worker_prod
    command: /start-celeryworker
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db
      - web

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_celery_beat_prod
    command: /start-celerybeat
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db
      - web

  flower:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_celery_flower_prod
    command: /start-flower
    env_file:
      - ./env/.prod
    expose:
      - 5555
    depends_on:
      - redis
      - db

  nginx:
    build:
      context: ./compose/prod/nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./ssl:/etc/nginx/ssl  # Mount SSL certificates
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"  # Flower
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
