services:
  nginx:
    build: ./compose/prod/nginx
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
      - /etc/letsencrypt/live/sillysongshop.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/sillysongshop.com/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "443:443/tcp"
      - "443:443/udp"  # HTTP/3 QUIC
      - "80:80"
      - "5555:5555/tcp"
      - "5555:5555/udp"  # HTTP/3 QUIC for Flower
    depends_on:
      - web
      - flower
    # Enable IPv6
    networks:
      - default
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  web:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    command: /start
    hostname: sillysongshop
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
      - logs:/app/logs
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.prod

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_celery_worker
    command: /start-celeryworker
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
      - logs:/app/logs
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_celery_beat
    command: /start-celerybeat
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
      - logs:/app/logs
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: sillysongshop_celery_flower
    command: /start-flower
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - ./env/.prod
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
  logs:

networks:
  default:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
