#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

/usr/local/bin/gunicorn weirdsongfactory.wsgi:application --bind [::]:8000 --chdir=/app
