# Generated by Django 4.2.7 on 2025-10-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("lyrics", models.TextField()),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday 🎉"),
                            ("anniversary", "Anniversary 💍"),
                            ("roast", "Roast 🥳"),
                            ("random", "Totally Random 🐒"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
