# Generated by Django 4.2.7 on 2025-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("child_birthday", "Child's Birthday 🎂"),
                    ("adult_birthday", "Adult Birthday 🎉"),
                    ("anniversary", "Anniversary 💍"),
                    ("roast", "Roast 🥳"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
