# Generated by Django 5.2.7 on 2025-10-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_status_order_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics 4 Measurement ID (e.g., G-XXXXXXXXXX)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Tag Manager Container ID (e.g., GTM-XXXXXXX)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(
                        blank=True,
                        help_text="Facebook Pixel ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "analytics_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable all analytics tracking"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analytics Settings",
                "verbose_name_plural": "Analytics Settings",
            },
        ),
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("referrer", models.URLField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("utm_term", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_visit", models.DateTimeField(auto_now_add=True)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("converted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Visitor Session",
                "verbose_name_plural": "Visitor Sessions",
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.URLField()),
                ("page_title", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "time_on_page",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent on page in seconds"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pageview_set",
                        to="orders.visitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
            },
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("form_submit", "Form Submission"),
                            ("payment_start", "Payment Started"),
                            ("payment_complete", "Payment Complete"),
                            ("email_signup", "Email Signup"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="orders.visitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion Event",
                "verbose_name_plural": "Conversion Events",
            },
        ),
    ]
