# Generated by Django 5.2.7 on 2025-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_analyticssettings_visitorsession_pageview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expedited_delivery",
            field=models.BooleanField(
                default=False, help_text="2-hour delivery for $10.99 extra"
            ),
        ),
    ]
